#![cfg_attr(not(test), warn(clippy::unwrap_used, clippy::expect_used))]

pub mod access_history;
pub mod actions;
pub mod claude_env;
pub mod context;
pub mod focus;
pub mod hook_monitor;
pub mod hooks;
pub mod lifecycle;
pub mod persistence;
pub mod remote_apply;
pub mod remote_sync;
#[cfg(feature = "gpui")]
pub mod request_broker;
#[cfg(feature = "gpui")]
pub mod requests;
pub mod sessions;
pub mod sidebar_controller;
pub mod settings;
pub mod state;
pub mod toast;
pub mod visibility;
#[cfg(feature = "gpui")]
pub mod worktree_sync;
