//! Quick worktree creation — the branch name is generated by the daemon (which
//! owns the git repo), then we dispatch `ActionRequest::CreateWorktree`. The
//! daemon owns the worktree creation (fetch + `git worktree add`), project
//! registration, terminal spawning and hooks; the new worktree project mirrors
//! back into the sidebar. The GUI never mutates its read-only mirror directly.

use super::Sidebar;
use gpui::*;
use okena_core::api::ActionRequest;

impl Sidebar {
    /// Resolve the remote connection params for a project:
    /// `(host, port, token, daemon-side project id)`. Returns `None` if the
    /// project has no connection, no matching remote connection, or no saved
    /// token.
    fn resolve_remote_params(
        &self,
        project_id: &str,
        cx: &App,
    ) -> Option<(String, u16, String, Option<okena_transport::client::LocalEndpoint>, String)> {
        let conn_id = self.workspace.read(cx).project(project_id)?.connection_id.clone()?;
        let get = self.get_remote_connections.as_ref()?;
        let config = get(cx).into_iter().find(|s| s.config.id == conn_id)?.config;
        let token = config.saved_token?;
        let daemon_id = okena_transport::client::strip_prefix(project_id, &conn_id);
        Some((config.host, config.port, token, config.local_endpoint, daemon_id))
    }

    /// Spawn quick worktree creation. The branch name is generated on the daemon
    /// via `ActionRequest::GenerateWorktreeBranchName` (the git repo lives there,
    /// so local generation fails in headless mode). The actual worktree creation
    /// is the daemon's job via `ActionRequest::CreateWorktree`.
    pub fn spawn_quick_create_worktree(&mut self, project_id: &str, cx: &mut Context<Self>) {
        // Debounce: prevent concurrent creation for the same parent
        if !self.creating_worktree.insert(project_id.to_string()) {
            return;
        }

        let parent_id = project_id.to_string();
        let parent_id_for_cleanup = parent_id.clone();

        // Resolve remote connection params on the main thread before spawning.
        // The daemon owns path resolution and branch-name generation.
        let Some((host, port, token, local_endpoint, daemon_id)) = self.resolve_remote_params(project_id, cx) else {
            log::error!("Quick worktree creation failed: could not resolve remote connection");
            self.creating_worktree.remove(project_id);
            return;
        };

        cx.spawn(async move |sidebar_weak, cx| {
            // Ask the daemon to generate the branch name off the main thread.
            // The client must know the branch before dispatching CreateWorktree
            // (visibility is keyed on it).
            let branch_result = smol::unblock(move || -> Result<String, String> {
                let action = ActionRequest::GenerateWorktreeBranchName { project_id: daemon_id };
                match okena_transport::remote_action::post_action_with_endpoint(
                    &host,
                    port,
                    &token,
                    local_endpoint.as_ref(),
                    action,
                ) {
                    Ok(Some(v)) => v
                        .get("branch")
                        .and_then(|b| b.as_str())
                        .map(String::from)
                        .ok_or_else(|| "missing branch in response".to_string()),
                    Ok(None) => Err("empty response".to_string()),
                    Err(e) => Err(e),
                }
            })
            .await;

            let branch = match branch_result {
                Ok(v) => v,
                Err(e) => {
                    log::error!("Quick worktree creation failed: {}", e);
                    let _ = sidebar_weak.update(cx, |sidebar, cx| {
                        sidebar.creating_worktree.remove(&parent_id_for_cleanup);
                        cx.notify();
                    });
                    return;
                }
            };

            // Dispatch CreateWorktree to the daemon. The dispatcher queues
            // pending visibility keyed by branch name and sends the action; the
            // new worktree project mirrors back when the daemon finishes.
            let _ = sidebar_weak.update(cx, |sidebar, cx| {
                sidebar.dispatch_action_for_project(
                    &parent_id,
                    ActionRequest::CreateWorktree {
                        project_id: parent_id.clone(),
                        branch,
                        create_branch: true,
                    },
                    cx,
                );
                sidebar.creating_worktree.remove(&parent_id_for_cleanup);
                cx.notify();
            });
        }).detach();
    }
}
