// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'connection.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Connect to an Okena remote server.
String connect({required String host, required int port}) =>
    RustLib.instance.api.crateApiConnectionConnect(host: host, port: port);

/// Pair with the server using a pairing code.
Future<void> pair({required String connId, required String code}) =>
    RustLib.instance.api.crateApiConnectionPair(connId: connId, code: code);

/// Disconnect from a server.
void disconnect({required String connId}) =>
    RustLib.instance.api.crateApiConnectionDisconnect(connId: connId);

/// Get current connection status.
ConnectionStatus connectionStatus({required String connId}) =>
    RustLib.instance.api.crateApiConnectionConnectionStatus(connId: connId);

@freezed
sealed class ConnectionStatus with _$ConnectionStatus {
  const ConnectionStatus._();

  const factory ConnectionStatus.disconnected() = ConnectionStatus_Disconnected;
  const factory ConnectionStatus.connecting() = ConnectionStatus_Connecting;
  const factory ConnectionStatus.connected() = ConnectionStatus_Connected;
  const factory ConnectionStatus.pairing() = ConnectionStatus_Pairing;
  const factory ConnectionStatus.error({required String message}) =
      ConnectionStatus_Error;
}
