// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/connection.dart';
import 'api/state.dart';
import 'api/terminal.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiConnectionInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 670473026;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'okena_mobile_native',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiConnectionConnect({required String host, required int port});

  ConnectionStatus crateApiConnectionConnectionStatus({required String connId});

  void crateApiConnectionDisconnect({required String connId});

  List<String> crateApiStateGetAllTerminalIds({required String connId});

  CursorState crateApiTerminalGetCursor({
    required String connId,
    required String terminalId,
  });

  String? crateApiStateGetFocusedProjectId({required String connId});

  List<ProjectInfo> crateApiStateGetProjects({required String connId});

  List<CellData> crateApiTerminalGetVisibleCells({
    required String connId,
    required String terminalId,
  });

  Future<void> crateApiConnectionInitApp();

  bool crateApiStateIsDirty({
    required String connId,
    required String terminalId,
  });

  Future<void> crateApiConnectionPair({
    required String connId,
    required String code,
  });

  Future<void> crateApiTerminalResizeTerminal({
    required String connId,
    required String terminalId,
    required int cols,
    required int rows,
  });

  Future<void> crateApiStateSendSpecialKey({
    required String connId,
    required String terminalId,
    required String key,
  });

  Future<void> crateApiTerminalSendText({
    required String connId,
    required String terminalId,
    required String text,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiConnectionConnect({required String host, required int port}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionConnectConstMeta,
        argValues: [host, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectConstMeta =>
      const TaskConstMeta(debugName: "connect", argNames: ["host", "port"]);

  @override
  ConnectionStatus crateApiConnectionConnectionStatus({
    required String connId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionConnectionStatusConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectionStatusConstMeta =>
      const TaskConstMeta(debugName: "connection_status", argNames: ["connId"]);

  @override
  void crateApiConnectionDisconnect({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionDisconnectConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionDisconnectConstMeta =>
      const TaskConstMeta(debugName: "disconnect", argNames: ["connId"]);

  @override
  List<String> crateApiStateGetAllTerminalIds({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetAllTerminalIdsConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetAllTerminalIdsConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_terminal_ids",
        argNames: ["connId"],
      );

  @override
  CursorState crateApiTerminalGetCursor({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cursor_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalGetCursorConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalGetCursorConstMeta => const TaskConstMeta(
    debugName: "get_cursor",
    argNames: ["connId", "terminalId"],
  );

  @override
  String? crateApiStateGetFocusedProjectId({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetFocusedProjectIdConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetFocusedProjectIdConstMeta =>
      const TaskConstMeta(
        debugName: "get_focused_project_id",
        argNames: ["connId"],
      );

  @override
  List<ProjectInfo> crateApiStateGetProjects({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_project_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetProjectsConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetProjectsConstMeta =>
      const TaskConstMeta(debugName: "get_projects", argNames: ["connId"]);

  @override
  List<CellData> crateApiTerminalGetVisibleCells({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_cell_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalGetVisibleCellsConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalGetVisibleCellsConstMeta =>
      const TaskConstMeta(
        debugName: "get_visible_cells",
        argNames: ["connId", "terminalId"],
      );

  @override
  Future<void> crateApiConnectionInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiStateIsDirty({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateIsDirtyConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateIsDirtyConstMeta => const TaskConstMeta(
    debugName: "is_dirty",
    argNames: ["connId", "terminalId"],
  );

  @override
  Future<void> crateApiConnectionPair({
    required String connId,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConnectionPairConstMeta,
        argValues: [connId, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionPairConstMeta =>
      const TaskConstMeta(debugName: "pair", argNames: ["connId", "code"]);

  @override
  Future<void> crateApiTerminalResizeTerminal({
    required String connId,
    required String terminalId,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_u_16(cols, serializer);
          sse_encode_u_16(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTerminalResizeTerminalConstMeta,
        argValues: [connId, terminalId, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalResizeTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "resize_terminal",
        argNames: ["connId", "terminalId", "cols", "rows"],
      );

  @override
  Future<void> crateApiStateSendSpecialKey({
    required String connId,
    required String terminalId,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateSendSpecialKeyConstMeta,
        argValues: [connId, terminalId, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateSendSpecialKeyConstMeta =>
      const TaskConstMeta(
        debugName: "send_special_key",
        argNames: ["connId", "terminalId", "key"],
      );

  @override
  Future<void> crateApiTerminalSendText({
    required String connId,
    required String terminalId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTerminalSendTextConstMeta,
        argValues: [connId, terminalId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalSendTextConstMeta => const TaskConstMeta(
    debugName: "send_text",
    argNames: ["connId", "terminalId", "text"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CellData dco_decode_cell_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CellData(
      character: dco_decode_String(arr[0]),
      fg: dco_decode_u_32(arr[1]),
      bg: dco_decode_u_32(arr[2]),
      flags: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ConnectionStatus_Disconnected();
      case 1:
        return ConnectionStatus_Connecting();
      case 2:
        return ConnectionStatus_Connected();
      case 3:
        return ConnectionStatus_Pairing();
      case 4:
        return ConnectionStatus_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CursorShape dco_decode_cursor_shape(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CursorShape.values[raw as int];
  }

  @protected
  CursorState dco_decode_cursor_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CursorState(
      col: dco_decode_u_16(arr[0]),
      row: dco_decode_u_16(arr[1]),
      shape: dco_decode_cursor_shape(arr[2]),
      visible: dco_decode_bool(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CellData> dco_decode_list_cell_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cell_data).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProjectInfo> dco_decode_list_project_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_project_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProjectInfo dco_decode_project_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProjectInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      isVisible: dco_decode_bool(arr[3]),
      terminalIds: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CellData sse_decode_cell_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_character = sse_decode_String(deserializer);
    var var_fg = sse_decode_u_32(deserializer);
    var var_bg = sse_decode_u_32(deserializer);
    var var_flags = sse_decode_u_8(deserializer);
    return CellData(
      character: var_character,
      fg: var_fg,
      bg: var_bg,
      flags: var_flags,
    );
  }

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ConnectionStatus_Disconnected();
      case 1:
        return ConnectionStatus_Connecting();
      case 2:
        return ConnectionStatus_Connected();
      case 3:
        return ConnectionStatus_Pairing();
      case 4:
        var var_message = sse_decode_String(deserializer);
        return ConnectionStatus_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CursorShape sse_decode_cursor_shape(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CursorShape.values[inner];
  }

  @protected
  CursorState sse_decode_cursor_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_col = sse_decode_u_16(deserializer);
    var var_row = sse_decode_u_16(deserializer);
    var var_shape = sse_decode_cursor_shape(deserializer);
    var var_visible = sse_decode_bool(deserializer);
    return CursorState(
      col: var_col,
      row: var_row,
      shape: var_shape,
      visible: var_visible,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CellData> sse_decode_list_cell_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CellData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cell_data(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProjectInfo> sse_decode_list_project_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectInfo sse_decode_project_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isVisible = sse_decode_bool(deserializer);
    var var_terminalIds = sse_decode_list_String(deserializer);
    return ProjectInfo(
      id: var_id,
      name: var_name,
      path: var_path,
      isVisible: var_isVisible,
      terminalIds: var_terminalIds,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_cell_data(CellData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.character, serializer);
    sse_encode_u_32(self.fg, serializer);
    sse_encode_u_32(self.bg, serializer);
    sse_encode_u_8(self.flags, serializer);
  }

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ConnectionStatus_Disconnected():
        sse_encode_i_32(0, serializer);
      case ConnectionStatus_Connecting():
        sse_encode_i_32(1, serializer);
      case ConnectionStatus_Connected():
        sse_encode_i_32(2, serializer);
      case ConnectionStatus_Pairing():
        sse_encode_i_32(3, serializer);
      case ConnectionStatus_Error(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_cursor_shape(CursorShape self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_cursor_state(CursorState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.col, serializer);
    sse_encode_u_16(self.row, serializer);
    sse_encode_cursor_shape(self.shape, serializer);
    sse_encode_bool(self.visible, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_cell_data(
    List<CellData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cell_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_project_info(
    List<ProjectInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_project_info(ProjectInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isVisible, serializer);
    sse_encode_list_String(self.terminalIds, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
