// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/connection.dart';
import 'api/state.dart';
import 'api/terminal.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiConnectionInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -142339940;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'okena_mobile_native',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiStateAddProject({
    required String connId,
    required String name,
    required String path,
  });

  void crateApiTerminalClearSelection({
    required String connId,
    required String terminalId,
  });

  Future<void> crateApiStateCloseTerminal({
    required String connId,
    required String projectId,
    required String terminalId,
  });

  Future<void> crateApiStateCloseTerminals({
    required String connId,
    required String projectId,
    required List<String> terminalIds,
  });

  String crateApiConnectionConnect({
    required String host,
    required int port,
    String? savedToken,
  });

  ConnectionStatus crateApiConnectionConnectionStatus({required String connId});

  Future<void> crateApiStateCreateTerminal({
    required String connId,
    required String projectId,
  });

  void crateApiConnectionDisconnect({required String connId});

  Future<void> crateApiStateFocusTerminal({
    required String connId,
    required String projectId,
    required String terminalId,
  });

  List<String> crateApiStateGetAllTerminalIds({required String connId});

  CursorState crateApiTerminalGetCursor({
    required String connId,
    required String terminalId,
  });

  String? crateApiStateGetFocusedProjectId({required String connId});

  List<FolderInfo> crateApiStateGetFolders({required String connId});

  FullscreenInfo? crateApiStateGetFullscreenTerminal({required String connId});

  String? crateApiStateGetProjectLayoutJson({
    required String connId,
    required String projectId,
  });

  List<String> crateApiStateGetProjectOrder({required String connId});

  List<ProjectInfo> crateApiStateGetProjects({required String connId});

  ScrollInfo crateApiTerminalGetScrollInfo({
    required String connId,
    required String terminalId,
  });

  String? crateApiTerminalGetSelectedText({
    required String connId,
    required String terminalId,
  });

  SelectionBounds? crateApiTerminalGetSelectionBounds({
    required String connId,
    required String terminalId,
  });

  String? crateApiConnectionGetToken({required String connId});

  List<CellData> crateApiTerminalGetVisibleCells({
    required String connId,
    required String terminalId,
  });

  Future<String> crateApiStateGitBranches({
    required String connId,
    required String projectId,
  });

  Future<String> crateApiStateGitDiff({
    required String connId,
    required String projectId,
    required String mode,
  });

  Future<String> crateApiStateGitDiffSummary({
    required String connId,
    required String projectId,
  });

  Future<String> crateApiStateGitStatus({
    required String connId,
    required String projectId,
  });

  Future<void> crateApiConnectionInitApp();

  bool crateApiStateIsDirty({
    required String connId,
    required String terminalId,
  });

  Future<void> crateApiConnectionPair({
    required String connId,
    required String code,
  });

  Future<String> crateApiStateReadContent({
    required String connId,
    required String terminalId,
  });

  Future<void> crateApiStateReloadServices({
    required String connId,
    required String projectId,
  });

  Future<void> crateApiStateRenameTerminal({
    required String connId,
    required String projectId,
    required String terminalId,
    required String name,
  });

  void crateApiTerminalResizeTerminal({
    required String connId,
    required String terminalId,
    required int cols,
    required int rows,
  });

  Future<void> crateApiStateRestartService({
    required String connId,
    required String projectId,
    required String serviceName,
  });

  Future<void> crateApiStateRunCommand({
    required String connId,
    required String terminalId,
    required String command,
  });

  void crateApiTerminalScroll({
    required String connId,
    required String terminalId,
    required int delta,
  });

  double crateApiConnectionSecondsSinceActivity({required String connId});

  Future<void> crateApiStateSendSpecialKey({
    required String connId,
    required String terminalId,
    required String key,
  });

  Future<void> crateApiTerminalSendText({
    required String connId,
    required String terminalId,
    required String text,
  });

  Future<void> crateApiStateSetFolderColor({
    required String connId,
    required String folderId,
    required String color,
  });

  Future<void> crateApiStateSetFullscreen({
    required String connId,
    required String projectId,
    String? terminalId,
  });

  Future<void> crateApiStateSetProjectColor({
    required String connId,
    required String projectId,
    required String color,
  });

  Future<void> crateApiStateSplitTerminal({
    required String connId,
    required String projectId,
    required Uint64List path,
    required String direction,
  });

  Future<void> crateApiStateStartAllServices({
    required String connId,
    required String projectId,
  });

  void crateApiTerminalStartSelection({
    required String connId,
    required String terminalId,
    required int col,
    required int row,
  });

  Future<void> crateApiStateStartService({
    required String connId,
    required String projectId,
    required String serviceName,
  });

  void crateApiTerminalStartWordSelection({
    required String connId,
    required String terminalId,
    required int col,
    required int row,
  });

  Future<void> crateApiStateStopAllServices({
    required String connId,
    required String projectId,
  });

  Future<void> crateApiStateStopService({
    required String connId,
    required String projectId,
    required String serviceName,
  });

  Future<void> crateApiStateToggleMinimized({
    required String connId,
    required String projectId,
    required String terminalId,
  });

  void crateApiTerminalUpdateSelection({
    required String connId,
    required String terminalId,
    required int col,
    required int row,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiStateAddProject({
    required String connId,
    required String name,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateAddProjectConstMeta,
        argValues: [connId, name, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateAddProjectConstMeta => const TaskConstMeta(
    debugName: "add_project",
    argNames: ["connId", "name", "path"],
  );

  @override
  void crateApiTerminalClearSelection({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalClearSelectionConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalClearSelectionConstMeta =>
      const TaskConstMeta(
        debugName: "clear_selection",
        argNames: ["connId", "terminalId"],
      );

  @override
  Future<void> crateApiStateCloseTerminal({
    required String connId,
    required String projectId,
    required String terminalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(terminalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateCloseTerminalConstMeta,
        argValues: [connId, projectId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateCloseTerminalConstMeta => const TaskConstMeta(
    debugName: "close_terminal",
    argNames: ["connId", "projectId", "terminalId"],
  );

  @override
  Future<void> crateApiStateCloseTerminals({
    required String connId,
    required String projectId,
    required List<String> terminalIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_list_String(terminalIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateCloseTerminalsConstMeta,
        argValues: [connId, projectId, terminalIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateCloseTerminalsConstMeta =>
      const TaskConstMeta(
        debugName: "close_terminals",
        argNames: ["connId", "projectId", "terminalIds"],
      );

  @override
  String crateApiConnectionConnect({
    required String host,
    required int port,
    String? savedToken,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_opt_String(savedToken, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionConnectConstMeta,
        argValues: [host, port, savedToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectConstMeta => const TaskConstMeta(
    debugName: "connect",
    argNames: ["host", "port", "savedToken"],
  );

  @override
  ConnectionStatus crateApiConnectionConnectionStatus({
    required String connId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionConnectionStatusConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionConnectionStatusConstMeta =>
      const TaskConstMeta(debugName: "connection_status", argNames: ["connId"]);

  @override
  Future<void> crateApiStateCreateTerminal({
    required String connId,
    required String projectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateCreateTerminalConstMeta,
        argValues: [connId, projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateCreateTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "create_terminal",
        argNames: ["connId", "projectId"],
      );

  @override
  void crateApiConnectionDisconnect({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionDisconnectConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionDisconnectConstMeta =>
      const TaskConstMeta(debugName: "disconnect", argNames: ["connId"]);

  @override
  Future<void> crateApiStateFocusTerminal({
    required String connId,
    required String projectId,
    required String terminalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(terminalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateFocusTerminalConstMeta,
        argValues: [connId, projectId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateFocusTerminalConstMeta => const TaskConstMeta(
    debugName: "focus_terminal",
    argNames: ["connId", "projectId", "terminalId"],
  );

  @override
  List<String> crateApiStateGetAllTerminalIds({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetAllTerminalIdsConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetAllTerminalIdsConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_terminal_ids",
        argNames: ["connId"],
      );

  @override
  CursorState crateApiTerminalGetCursor({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cursor_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalGetCursorConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalGetCursorConstMeta => const TaskConstMeta(
    debugName: "get_cursor",
    argNames: ["connId", "terminalId"],
  );

  @override
  String? crateApiStateGetFocusedProjectId({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetFocusedProjectIdConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetFocusedProjectIdConstMeta =>
      const TaskConstMeta(
        debugName: "get_focused_project_id",
        argNames: ["connId"],
      );

  @override
  List<FolderInfo> crateApiStateGetFolders({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_folder_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetFoldersConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetFoldersConstMeta =>
      const TaskConstMeta(debugName: "get_folders", argNames: ["connId"]);

  @override
  FullscreenInfo? crateApiStateGetFullscreenTerminal({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_fullscreen_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetFullscreenTerminalConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetFullscreenTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "get_fullscreen_terminal",
        argNames: ["connId"],
      );

  @override
  String? crateApiStateGetProjectLayoutJson({
    required String connId,
    required String projectId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetProjectLayoutJsonConstMeta,
        argValues: [connId, projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetProjectLayoutJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_project_layout_json",
        argNames: ["connId", "projectId"],
      );

  @override
  List<String> crateApiStateGetProjectOrder({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetProjectOrderConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetProjectOrderConstMeta =>
      const TaskConstMeta(debugName: "get_project_order", argNames: ["connId"]);

  @override
  List<ProjectInfo> crateApiStateGetProjects({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_project_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateGetProjectsConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGetProjectsConstMeta =>
      const TaskConstMeta(debugName: "get_projects", argNames: ["connId"]);

  @override
  ScrollInfo crateApiTerminalGetScrollInfo({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scroll_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalGetScrollInfoConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalGetScrollInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_scroll_info",
        argNames: ["connId", "terminalId"],
      );

  @override
  String? crateApiTerminalGetSelectedText({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalGetSelectedTextConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalGetSelectedTextConstMeta =>
      const TaskConstMeta(
        debugName: "get_selected_text",
        argNames: ["connId", "terminalId"],
      );

  @override
  SelectionBounds? crateApiTerminalGetSelectionBounds({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_selection_bounds,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalGetSelectionBoundsConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalGetSelectionBoundsConstMeta =>
      const TaskConstMeta(
        debugName: "get_selection_bounds",
        argNames: ["connId", "terminalId"],
      );

  @override
  String? crateApiConnectionGetToken({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionGetTokenConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionGetTokenConstMeta =>
      const TaskConstMeta(debugName: "get_token", argNames: ["connId"]);

  @override
  List<CellData> crateApiTerminalGetVisibleCells({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_cell_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalGetVisibleCellsConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalGetVisibleCellsConstMeta =>
      const TaskConstMeta(
        debugName: "get_visible_cells",
        argNames: ["connId", "terminalId"],
      );

  @override
  Future<String> crateApiStateGitBranches({
    required String connId,
    required String projectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateGitBranchesConstMeta,
        argValues: [connId, projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGitBranchesConstMeta => const TaskConstMeta(
    debugName: "git_branches",
    argNames: ["connId", "projectId"],
  );

  @override
  Future<String> crateApiStateGitDiff({
    required String connId,
    required String projectId,
    required String mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateGitDiffConstMeta,
        argValues: [connId, projectId, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGitDiffConstMeta => const TaskConstMeta(
    debugName: "git_diff",
    argNames: ["connId", "projectId", "mode"],
  );

  @override
  Future<String> crateApiStateGitDiffSummary({
    required String connId,
    required String projectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateGitDiffSummaryConstMeta,
        argValues: [connId, projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGitDiffSummaryConstMeta =>
      const TaskConstMeta(
        debugName: "git_diff_summary",
        argNames: ["connId", "projectId"],
      );

  @override
  Future<String> crateApiStateGitStatus({
    required String connId,
    required String projectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateGitStatusConstMeta,
        argValues: [connId, projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateGitStatusConstMeta => const TaskConstMeta(
    debugName: "git_status",
    argNames: ["connId", "projectId"],
  );

  @override
  Future<void> crateApiConnectionInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiStateIsDirty({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateIsDirtyConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateIsDirtyConstMeta => const TaskConstMeta(
    debugName: "is_dirty",
    argNames: ["connId", "terminalId"],
  );

  @override
  Future<void> crateApiConnectionPair({
    required String connId,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConnectionPairConstMeta,
        argValues: [connId, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionPairConstMeta =>
      const TaskConstMeta(debugName: "pair", argNames: ["connId", "code"]);

  @override
  Future<String> crateApiStateReadContent({
    required String connId,
    required String terminalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateReadContentConstMeta,
        argValues: [connId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateReadContentConstMeta => const TaskConstMeta(
    debugName: "read_content",
    argNames: ["connId", "terminalId"],
  );

  @override
  Future<void> crateApiStateReloadServices({
    required String connId,
    required String projectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateReloadServicesConstMeta,
        argValues: [connId, projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateReloadServicesConstMeta =>
      const TaskConstMeta(
        debugName: "reload_services",
        argNames: ["connId", "projectId"],
      );

  @override
  Future<void> crateApiStateRenameTerminal({
    required String connId,
    required String projectId,
    required String terminalId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateRenameTerminalConstMeta,
        argValues: [connId, projectId, terminalId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateRenameTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "rename_terminal",
        argNames: ["connId", "projectId", "terminalId", "name"],
      );

  @override
  void crateApiTerminalResizeTerminal({
    required String connId,
    required String terminalId,
    required int cols,
    required int rows,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_u_16(cols, serializer);
          sse_encode_u_16(rows, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalResizeTerminalConstMeta,
        argValues: [connId, terminalId, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalResizeTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "resize_terminal",
        argNames: ["connId", "terminalId", "cols", "rows"],
      );

  @override
  Future<void> crateApiStateRestartService({
    required String connId,
    required String projectId,
    required String serviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(serviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateRestartServiceConstMeta,
        argValues: [connId, projectId, serviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateRestartServiceConstMeta =>
      const TaskConstMeta(
        debugName: "restart_service",
        argNames: ["connId", "projectId", "serviceName"],
      );

  @override
  Future<void> crateApiStateRunCommand({
    required String connId,
    required String terminalId,
    required String command,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_String(command, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateRunCommandConstMeta,
        argValues: [connId, terminalId, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateRunCommandConstMeta => const TaskConstMeta(
    debugName: "run_command",
    argNames: ["connId", "terminalId", "command"],
  );

  @override
  void crateApiTerminalScroll({
    required String connId,
    required String terminalId,
    required int delta,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_i_32(delta, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalScrollConstMeta,
        argValues: [connId, terminalId, delta],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalScrollConstMeta => const TaskConstMeta(
    debugName: "scroll",
    argNames: ["connId", "terminalId", "delta"],
  );

  @override
  double crateApiConnectionSecondsSinceActivity({required String connId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionSecondsSinceActivityConstMeta,
        argValues: [connId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionSecondsSinceActivityConstMeta =>
      const TaskConstMeta(
        debugName: "seconds_since_activity",
        argNames: ["connId"],
      );

  @override
  Future<void> crateApiStateSendSpecialKey({
    required String connId,
    required String terminalId,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateSendSpecialKeyConstMeta,
        argValues: [connId, terminalId, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateSendSpecialKeyConstMeta =>
      const TaskConstMeta(
        debugName: "send_special_key",
        argNames: ["connId", "terminalId", "key"],
      );

  @override
  Future<void> crateApiTerminalSendText({
    required String connId,
    required String terminalId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTerminalSendTextConstMeta,
        argValues: [connId, terminalId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalSendTextConstMeta => const TaskConstMeta(
    debugName: "send_text",
    argNames: ["connId", "terminalId", "text"],
  );

  @override
  Future<void> crateApiStateSetFolderColor({
    required String connId,
    required String folderId,
    required String color,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(folderId, serializer);
          sse_encode_String(color, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateSetFolderColorConstMeta,
        argValues: [connId, folderId, color],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateSetFolderColorConstMeta =>
      const TaskConstMeta(
        debugName: "set_folder_color",
        argNames: ["connId", "folderId", "color"],
      );

  @override
  Future<void> crateApiStateSetFullscreen({
    required String connId,
    required String projectId,
    String? terminalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_opt_String(terminalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateSetFullscreenConstMeta,
        argValues: [connId, projectId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateSetFullscreenConstMeta => const TaskConstMeta(
    debugName: "set_fullscreen",
    argNames: ["connId", "projectId", "terminalId"],
  );

  @override
  Future<void> crateApiStateSetProjectColor({
    required String connId,
    required String projectId,
    required String color,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(color, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateSetProjectColorConstMeta,
        argValues: [connId, projectId, color],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateSetProjectColorConstMeta =>
      const TaskConstMeta(
        debugName: "set_project_color",
        argNames: ["connId", "projectId", "color"],
      );

  @override
  Future<void> crateApiStateSplitTerminal({
    required String connId,
    required String projectId,
    required Uint64List path,
    required String direction,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_list_prim_usize_strict(path, serializer);
          sse_encode_String(direction, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateSplitTerminalConstMeta,
        argValues: [connId, projectId, path, direction],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateSplitTerminalConstMeta => const TaskConstMeta(
    debugName: "split_terminal",
    argNames: ["connId", "projectId", "path", "direction"],
  );

  @override
  Future<void> crateApiStateStartAllServices({
    required String connId,
    required String projectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateStartAllServicesConstMeta,
        argValues: [connId, projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateStartAllServicesConstMeta =>
      const TaskConstMeta(
        debugName: "start_all_services",
        argNames: ["connId", "projectId"],
      );

  @override
  void crateApiTerminalStartSelection({
    required String connId,
    required String terminalId,
    required int col,
    required int row,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_u_16(row, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalStartSelectionConstMeta,
        argValues: [connId, terminalId, col, row],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalStartSelectionConstMeta =>
      const TaskConstMeta(
        debugName: "start_selection",
        argNames: ["connId", "terminalId", "col", "row"],
      );

  @override
  Future<void> crateApiStateStartService({
    required String connId,
    required String projectId,
    required String serviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(serviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateStartServiceConstMeta,
        argValues: [connId, projectId, serviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateStartServiceConstMeta => const TaskConstMeta(
    debugName: "start_service",
    argNames: ["connId", "projectId", "serviceName"],
  );

  @override
  void crateApiTerminalStartWordSelection({
    required String connId,
    required String terminalId,
    required int col,
    required int row,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_u_16(row, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 47)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalStartWordSelectionConstMeta,
        argValues: [connId, terminalId, col, row],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalStartWordSelectionConstMeta =>
      const TaskConstMeta(
        debugName: "start_word_selection",
        argNames: ["connId", "terminalId", "col", "row"],
      );

  @override
  Future<void> crateApiStateStopAllServices({
    required String connId,
    required String projectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateStopAllServicesConstMeta,
        argValues: [connId, projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateStopAllServicesConstMeta =>
      const TaskConstMeta(
        debugName: "stop_all_services",
        argNames: ["connId", "projectId"],
      );

  @override
  Future<void> crateApiStateStopService({
    required String connId,
    required String projectId,
    required String serviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(serviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateStopServiceConstMeta,
        argValues: [connId, projectId, serviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateStopServiceConstMeta => const TaskConstMeta(
    debugName: "stop_service",
    argNames: ["connId", "projectId", "serviceName"],
  );

  @override
  Future<void> crateApiStateToggleMinimized({
    required String connId,
    required String projectId,
    required String terminalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(projectId, serializer);
          sse_encode_String(terminalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStateToggleMinimizedConstMeta,
        argValues: [connId, projectId, terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateToggleMinimizedConstMeta =>
      const TaskConstMeta(
        debugName: "toggle_minimized",
        argNames: ["connId", "projectId", "terminalId"],
      );

  @override
  void crateApiTerminalUpdateSelection({
    required String connId,
    required String terminalId,
    required int col,
    required int row,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connId, serializer);
          sse_encode_String(terminalId, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_u_16(row, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 51)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalUpdateSelectionConstMeta,
        argValues: [connId, terminalId, col, row],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalUpdateSelectionConstMeta =>
      const TaskConstMeta(
        debugName: "update_selection",
        argNames: ["connId", "terminalId", "col", "row"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FullscreenInfo dco_decode_box_autoadd_fullscreen_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fullscreen_info(raw);
  }

  @protected
  SelectionBounds dco_decode_box_autoadd_selection_bounds(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_selection_bounds(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CellData dco_decode_cell_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CellData(
      character: dco_decode_String(arr[0]),
      fg: dco_decode_u_32(arr[1]),
      bg: dco_decode_u_32(arr[2]),
      flags: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ConnectionStatus_Disconnected();
      case 1:
        return ConnectionStatus_Connecting();
      case 2:
        return ConnectionStatus_Connected();
      case 3:
        return ConnectionStatus_Pairing();
      case 4:
        return ConnectionStatus_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CursorShape dco_decode_cursor_shape(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CursorShape.values[raw as int];
  }

  @protected
  CursorState dco_decode_cursor_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CursorState(
      col: dco_decode_u_16(arr[0]),
      row: dco_decode_u_16(arr[1]),
      shape: dco_decode_cursor_shape(arr[2]),
      visible: dco_decode_bool(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FolderInfo dco_decode_folder_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FolderInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      projectIds: dco_decode_list_String(arr[2]),
      folderColor: dco_decode_String(arr[3]),
    );
  }

  @protected
  FullscreenInfo dco_decode_fullscreen_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FullscreenInfo(
      projectId: dco_decode_String(arr[0]),
      terminalId: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CellData> dco_decode_list_cell_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cell_data).toList();
  }

  @protected
  List<FolderInfo> dco_decode_list_folder_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_folder_info).toList();
  }

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint64List;
  }

  @protected
  List<ProjectInfo> dco_decode_list_project_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_project_info).toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<ServiceInfo> dco_decode_list_service_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_service_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FullscreenInfo? dco_decode_opt_box_autoadd_fullscreen_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_fullscreen_info(raw);
  }

  @protected
  SelectionBounds? dco_decode_opt_box_autoadd_selection_bounds(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_selection_bounds(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  ProjectInfo dco_decode_project_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ProjectInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      showInOverview: dco_decode_bool(arr[3]),
      terminalIds: dco_decode_list_String(arr[4]),
      terminalNames: dco_decode_Map_String_String_None(arr[5]),
      gitBranch: dco_decode_opt_String(arr[6]),
      gitLinesAdded: dco_decode_u_32(arr[7]),
      gitLinesRemoved: dco_decode_u_32(arr[8]),
      services: dco_decode_list_service_info(arr[9]),
      folderColor: dco_decode_String(arr[10]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  ScrollInfo dco_decode_scroll_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ScrollInfo(
      totalLines: dco_decode_u_32(arr[0]),
      visibleLines: dco_decode_u_32(arr[1]),
      displayOffset: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  SelectionBounds dco_decode_selection_bounds(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SelectionBounds(
      startCol: dco_decode_u_16(arr[0]),
      startRow: dco_decode_i_32(arr[1]),
      endCol: dco_decode_u_16(arr[2]),
      endRow: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  ServiceInfo dco_decode_service_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ServiceInfo(
      name: dco_decode_String(arr[0]),
      status: dco_decode_String(arr[1]),
      terminalId: dco_decode_opt_String(arr[2]),
      ports: dco_decode_list_prim_u_16_strict(arr[3]),
      exitCode: dco_decode_opt_box_autoadd_u_32(arr[4]),
      kind: dco_decode_String(arr[5]),
      isExtra: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FullscreenInfo sse_decode_box_autoadd_fullscreen_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fullscreen_info(deserializer));
  }

  @protected
  SelectionBounds sse_decode_box_autoadd_selection_bounds(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_selection_bounds(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CellData sse_decode_cell_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_character = sse_decode_String(deserializer);
    var var_fg = sse_decode_u_32(deserializer);
    var var_bg = sse_decode_u_32(deserializer);
    var var_flags = sse_decode_u_8(deserializer);
    return CellData(
      character: var_character,
      fg: var_fg,
      bg: var_bg,
      flags: var_flags,
    );
  }

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ConnectionStatus_Disconnected();
      case 1:
        return ConnectionStatus_Connecting();
      case 2:
        return ConnectionStatus_Connected();
      case 3:
        return ConnectionStatus_Pairing();
      case 4:
        var var_message = sse_decode_String(deserializer);
        return ConnectionStatus_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CursorShape sse_decode_cursor_shape(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CursorShape.values[inner];
  }

  @protected
  CursorState sse_decode_cursor_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_col = sse_decode_u_16(deserializer);
    var var_row = sse_decode_u_16(deserializer);
    var var_shape = sse_decode_cursor_shape(deserializer);
    var var_visible = sse_decode_bool(deserializer);
    return CursorState(
      col: var_col,
      row: var_row,
      shape: var_shape,
      visible: var_visible,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FolderInfo sse_decode_folder_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_projectIds = sse_decode_list_String(deserializer);
    var var_folderColor = sse_decode_String(deserializer);
    return FolderInfo(
      id: var_id,
      name: var_name,
      projectIds: var_projectIds,
      folderColor: var_folderColor,
    );
  }

  @protected
  FullscreenInfo sse_decode_fullscreen_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectId = sse_decode_String(deserializer);
    var var_terminalId = sse_decode_String(deserializer);
    return FullscreenInfo(projectId: var_projectId, terminalId: var_terminalId);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CellData> sse_decode_list_cell_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CellData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cell_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<FolderInfo> sse_decode_list_folder_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FolderInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_folder_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  List<ProjectInfo> sse_decode_list_project_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<ServiceInfo> sse_decode_list_service_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ServiceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_service_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FullscreenInfo? sse_decode_opt_box_autoadd_fullscreen_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_fullscreen_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SelectionBounds? sse_decode_opt_box_autoadd_selection_bounds(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_selection_bounds(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectInfo sse_decode_project_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_showInOverview = sse_decode_bool(deserializer);
    var var_terminalIds = sse_decode_list_String(deserializer);
    var var_terminalNames = sse_decode_Map_String_String_None(deserializer);
    var var_gitBranch = sse_decode_opt_String(deserializer);
    var var_gitLinesAdded = sse_decode_u_32(deserializer);
    var var_gitLinesRemoved = sse_decode_u_32(deserializer);
    var var_services = sse_decode_list_service_info(deserializer);
    var var_folderColor = sse_decode_String(deserializer);
    return ProjectInfo(
      id: var_id,
      name: var_name,
      path: var_path,
      showInOverview: var_showInOverview,
      terminalIds: var_terminalIds,
      terminalNames: var_terminalNames,
      gitBranch: var_gitBranch,
      gitLinesAdded: var_gitLinesAdded,
      gitLinesRemoved: var_gitLinesRemoved,
      services: var_services,
      folderColor: var_folderColor,
    );
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  ScrollInfo sse_decode_scroll_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalLines = sse_decode_u_32(deserializer);
    var var_visibleLines = sse_decode_u_32(deserializer);
    var var_displayOffset = sse_decode_u_32(deserializer);
    return ScrollInfo(
      totalLines: var_totalLines,
      visibleLines: var_visibleLines,
      displayOffset: var_displayOffset,
    );
  }

  @protected
  SelectionBounds sse_decode_selection_bounds(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startCol = sse_decode_u_16(deserializer);
    var var_startRow = sse_decode_i_32(deserializer);
    var var_endCol = sse_decode_u_16(deserializer);
    var var_endRow = sse_decode_i_32(deserializer);
    return SelectionBounds(
      startCol: var_startCol,
      startRow: var_startRow,
      endCol: var_endCol,
      endRow: var_endRow,
    );
  }

  @protected
  ServiceInfo sse_decode_service_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_terminalId = sse_decode_opt_String(deserializer);
    var var_ports = sse_decode_list_prim_u_16_strict(deserializer);
    var var_exitCode = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_isExtra = sse_decode_bool(deserializer);
    return ServiceInfo(
      name: var_name,
      status: var_status,
      terminalId: var_terminalId,
      ports: var_ports,
      exitCode: var_exitCode,
      kind: var_kind,
      isExtra: var_isExtra,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_fullscreen_info(
    FullscreenInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fullscreen_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_selection_bounds(
    SelectionBounds self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_selection_bounds(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_cell_data(CellData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.character, serializer);
    sse_encode_u_32(self.fg, serializer);
    sse_encode_u_32(self.bg, serializer);
    sse_encode_u_8(self.flags, serializer);
  }

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ConnectionStatus_Disconnected():
        sse_encode_i_32(0, serializer);
      case ConnectionStatus_Connecting():
        sse_encode_i_32(1, serializer);
      case ConnectionStatus_Connected():
        sse_encode_i_32(2, serializer);
      case ConnectionStatus_Pairing():
        sse_encode_i_32(3, serializer);
      case ConnectionStatus_Error(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_cursor_shape(CursorShape self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_cursor_state(CursorState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.col, serializer);
    sse_encode_u_16(self.row, serializer);
    sse_encode_cursor_shape(self.shape, serializer);
    sse_encode_bool(self.visible, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_folder_info(FolderInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.projectIds, serializer);
    sse_encode_String(self.folderColor, serializer);
  }

  @protected
  void sse_encode_fullscreen_info(
    FullscreenInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectId, serializer);
    sse_encode_String(self.terminalId, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_cell_data(
    List<CellData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cell_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_folder_info(
    List<FolderInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_folder_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_project_info(
    List<ProjectInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_service_info(
    List<ServiceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_service_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_fullscreen_info(
    FullscreenInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_fullscreen_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_selection_bounds(
    SelectionBounds? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_selection_bounds(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_project_info(ProjectInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.showInOverview, serializer);
    sse_encode_list_String(self.terminalIds, serializer);
    sse_encode_Map_String_String_None(self.terminalNames, serializer);
    sse_encode_opt_String(self.gitBranch, serializer);
    sse_encode_u_32(self.gitLinesAdded, serializer);
    sse_encode_u_32(self.gitLinesRemoved, serializer);
    sse_encode_list_service_info(self.services, serializer);
    sse_encode_String(self.folderColor, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_scroll_info(ScrollInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.totalLines, serializer);
    sse_encode_u_32(self.visibleLines, serializer);
    sse_encode_u_32(self.displayOffset, serializer);
  }

  @protected
  void sse_encode_selection_bounds(
    SelectionBounds self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.startCol, serializer);
    sse_encode_i_32(self.startRow, serializer);
    sse_encode_u_16(self.endCol, serializer);
    sse_encode_i_32(self.endRow, serializer);
  }

  @protected
  void sse_encode_service_info(ServiceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.terminalId, serializer);
    sse_encode_list_prim_u_16_strict(self.ports, serializer);
    sse_encode_opt_box_autoadd_u_32(self.exitCode, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_bool(self.isExtra, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
